# Site settings
title: Lauri Kainulainen Inc.
email: lauri.kainulainen@gmail.com	
description: > # this means to ignore newlines until "baseurl:"
  Who is Lauri Kainulainen? What does he do? What right does he have to 
  show up in my search results?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lauri.sokkelo.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [migration, pull_me]

picture:
  source: images
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: full-width
        itemprop: image
      source_lrg:
        media: "(min-width: 1200px)"
        width: 1600
      source_med:
        media: "(min-width: 900px)"
        width: 1200
      source_default:
        width: 600


#    # Half width pictures
#    half:
#      ppi: [1, 1.5]
#      attr:
#        data-location: "{{location}}"
#        data-active: nil
#      source_lrg:
#        media: "(min-width: 40em)"
#        width: 400
#      source_med:
#        media: "(min-width: 30em)"
#        width: 250
#      source_default:
#        width: 350
#    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
#    gallery:
#      source_wide_hi:
#        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
#        width: 900
#        height: 600
#      source_wide:
#        media: "(min-width: 40em)"
#        width: 600
#        height: 400
#      source_default:
#        width: 250
#        height: 250
