# Site settings
title: Lauri Kainulainen Inc.
email: lauri.kainulainen@gmail.com	
description: > # this means to ignore newlines until "baseurl:"
  Who is Lauri Kainulainen? What does he do? What right does he have to 
  show up in my search results?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lauri.sokkelo.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [migration]